//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WixToolset.Data
{
    using System;
    using System.Reflection;
    using System.Resources;
    
    
    public class WixDataErrorEventArgs : MessageEventArgs
    {
        
        private static ResourceManager resourceManager = new ResourceManager("WixToolset.Data.Data.Messages", Assembly.GetExecutingAssembly());
        
        public WixDataErrorEventArgs(SourceLineNumber sourceLineNumbers, int id, string resourceName, params object[] messageArgs) : 
                base(sourceLineNumbers, id, resourceName, messageArgs)
        {
            base.Level = MessageLevel.Error;
            base.ResourceManager = resourceManager;
        }
    }
    
    public sealed class WixDataErrors
    {
        
        private WixDataErrors()
        {
        }
        
        public static MessageEventArgs UnexpectedFileFormat(string path, string expectedFormat, string actualFormat)
        {
            return new WixDataErrorEventArgs(null, 1, "WixDataErrors_UnexpectedFileFormat_1", path, expectedFormat, actualFormat);
        }
        
        public static MessageEventArgs CorruptFileFormat(string path, string format)
        {
            return new WixDataErrorEventArgs(null, 2, "WixDataErrors_CorruptFileFormat_1", path, format);
        }
        
        public static MessageEventArgs InvalidFileName(SourceLineNumber sourceLineNumbers, string fileName)
        {
            return new WixDataErrorEventArgs(sourceLineNumbers, 85, "WixDataErrors_InvalidFileName_1", fileName);
        }
        
        public static MessageEventArgs DuplicateLocalizationIdentifier(SourceLineNumber sourceLineNumbers, string localizationId)
        {
            return new WixDataErrorEventArgs(sourceLineNumbers, 100, "WixDataErrors_DuplicateLocalizationIdentifier_1", localizationId);
        }
        
        public static MessageEventArgs FileNotFound(SourceLineNumber sourceLineNumbers, string file)
        {
            return new WixDataErrorEventArgs(sourceLineNumbers, 103, "WixDataErrors_FileNotFound_1", file);
        }
        
        public static MessageEventArgs FileNotFound(SourceLineNumber sourceLineNumbers, string file, string fileType)
        {
            return new WixDataErrorEventArgs(sourceLineNumbers, 103, "WixDataErrors_FileNotFound_2", file, fileType);
        }
        
        public static MessageEventArgs DuplicatePrimaryKey(SourceLineNumber sourceLineNumbers, string primaryKey, string tableName)
        {
            return new WixDataErrorEventArgs(sourceLineNumbers, 130, "WixDataErrors_DuplicatePrimaryKey_1", primaryKey, tableName);
        }
        
        public static MessageEventArgs InvalidIdt(SourceLineNumber sourceLineNumbers, string idtFile)
        {
            return new WixDataErrorEventArgs(sourceLineNumbers, 136, "WixDataErrors_InvalidIdt_1", idtFile);
        }
        
        public static MessageEventArgs InvalidIdt(SourceLineNumber sourceLineNumbers, string idtFile, string tableName)
        {
            return new WixDataErrorEventArgs(sourceLineNumbers, 136, "WixDataErrors_InvalidIdt_2", idtFile, tableName);
        }
        
        public static MessageEventArgs VersionMismatch(SourceLineNumber sourceLineNumbers, string fileType, string version, string expectedVersion)
        {
            return new WixDataErrorEventArgs(sourceLineNumbers, 141, "WixDataErrors_VersionMismatch_1", fileType, version, expectedVersion);
        }
        
        public static MessageEventArgs IllegalFileCompressionAttributes(SourceLineNumber sourceLineNumbers)
        {
            return new WixDataErrorEventArgs(sourceLineNumbers, 167, "WixDataErrors_IllegalFileCompressionAttributes_1");
        }
        
        public static MessageEventArgs MissingTableDefinition(string tableName)
        {
            return new WixDataErrorEventArgs(null, 182, "WixDataErrors_MissingTableDefinition_1", tableName);
        }
        
        public static MessageEventArgs RealTableMissingPrimaryKeyColumn(SourceLineNumber sourceLineNumbers, string tableName)
        {
            return new WixDataErrorEventArgs(sourceLineNumbers, 225, "WixDataErrors_RealTableMissingPrimaryKeyColumn_1", tableName);
        }
        
        public static MessageEventArgs PathTooLong(SourceLineNumber sourceLineNumbers, string fileName)
        {
            return new WixDataErrorEventArgs(sourceLineNumbers, 262, "WixDataErrors_PathTooLong_1", fileName);
        }
        
        public static MessageEventArgs InvalidStringForCodepage(SourceLineNumber sourceLineNumbers, string codepage)
        {
            return new WixDataErrorEventArgs(sourceLineNumbers, 311, "WixDataErrors_InvalidStringForCodepage_1", codepage);
        }
        
        public static MessageEventArgs TooManyColumnsInRealTable(string tableName, int columnCount, int supportedColumnCount)
        {
            return new WixDataErrorEventArgs(null, 386, "WixDataErrors_TooManyColumnsInRealTable_1", tableName, columnCount, supportedColumnCount);
        }
    }
}
