#pragma once
// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated from SomeVerInfo.rc.
//  </auto-generated>
// ------------------------------------------------------------------------------

#if defined(_UNICODE)
#define CREATE_VERSION_STRING(x) L ## #x
#else
#define CREATE_VERSION_STRING(x) #x
#endif

#define CVS(x) CREATE_VERSION_STRING(x)

#ifdef RC_INVOKED

#include <winres.h>

VS_VERSION_INFO VERSIONINFO
  FILEVERSION     {major},{minor},{patch},{fullheight}
  PRODUCTVERSION  {major},{minor},0,0
  FILEFLAGSMASK   0x3FL
#ifdef _DEBUG
  FILEFLAGS       0x1L
#else
  FILEFLAGS       0x0L
#endif
  FILEOS          0x4L
  FILETYPE        SOMEVER_FILE_TYPE
  FILESUBTYPE     0x0L
BEGIN
  BLOCK "StringFileInfo"
  BEGIN
    BLOCK CVS(SOMEVER_VERSION_BLOCK)
    BEGIN
      VALUE "CompanyName", CVS(SOMEVER_COMPANY)
      VALUE "FileDescription", CVS(SOMEVER_TITLE)
      VALUE "FileVersion", CVS({fileversion})
      VALUE "InternalName", CVS(SOMEVER_INTERNAL_NAME)
      VALUE "OriginalFilename", CVS(SOMEVER_FILE_NAME)
      VALUE "ProductName", CVS(SOMEVER_PRODUCT)
      VALUE "ProductVersion", CVS({informationalversion})
      VALUE "LegalCopyright", CVS(SOMEVER_COPYRIGHT)
    END
  END
  BLOCK "VarFileInfo"
  BEGIN
    VALUE "Translation", SOMEVER_LCID, SOMEVER_CODEPAGE
  END
END
#endif
