#pragma once
// Copyright (c) .NET Foundation and contributors. All rights reserved. Licensed under the Microsoft Reciprocal License. See LICENSE.TXT file in the project root for full license information.


#define CB_CERTIFICATE_HASH 20

// Certificate.Attribute
enum SCA_CERT_ATTRIBUTES
{
    SCA_CERT_ATTRIBUTE_DEFAULT = 0,
    SCA_CERT_ATTRIBUTE_REQUEST = 1,
    SCA_CERT_ATTRIBUTE_BINARYDATA = 2,
    SCA_CERT_ATTRIBUTE_OVERWRITE = 4,
    SCA_CERT_ATTRIBUTE_VITAL = 8,
};


// Certificate.StoreLocation
enum SCA_CERTSYSTEMSTORE
{
    SCA_CERTSYSTEMSTORE_CURRENTUSER = 1,
    SCA_CERTSYSTEMSTORE_LOCALMACHINE = 2,
    SCA_CERTSYSTEMSTORE_SERVICES = 3,
    SCA_CERTSYSTEMSTORE_USERS = 4,
    SCA_CERTSYSTEMSTORE_USER_POLICY = 5,
    SCA_CERTSYSTEMSTORE_LOCALMACHINE_POLICY = 6,
    SCA_CERTSYSTEMSTORE_LOCALMACHINE_ENTERPRISE = 7,
};
