<?xml version="1.0" encoding="utf-8"?>
<!-- Copyright (c) .NET Foundation and contributors. All rights reserved. Licensed under the Microsoft Reciprocal License. See LICENSE.TXT file in the project root for full license information. -->

<Project>
  <!-- Overrides the standard Cpp.Build.props to include the PlatformToolset in the output path. -->
  <PropertyGroup>
    <IntDir>$(BaseIntermediateOutputPath)$(Configuration)\$(PlatformToolset)\$(PlatformTarget)\</IntDir>
    <IntDir Condition=" '$(Platform)' == 'ARM64EC' ">$(BaseIntermediateOutputPath)$(Configuration)\ARM64EC\</IntDir>
    <OutDir>$(OutputPath)$(PlatformToolset)\$(PlatformTarget)\</OutDir>
    <OutDir Condition=" '$(Platform)' == 'ARM64EC' ">$(OutputPath)$(PlatformToolset)\ARM64EC\</OutDir>
  </PropertyGroup>
</Project>
